### ISSUE TITLE
Never Ends

### ISSUE THREAD

**Issue by alexzk1** [linuxgurugamer/TacFuelBalancer#2]
Installed plugin on Linux 1.8.1 game.
It asked me to allow to check updates - I allowed, and now I have never ending funny pics ... not sure if updater problem or plugin itself.

Manualy edit xml file to disallow check, got a log:

> Executing: MiniAVC - 1.4.1.1
Assembly: /mnt/ssd120/alex/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/TacFuelBalancer/MiniAVC.dll

[Log 02:28:52.1763440]: Config not found
[Log 02:28:52.5598620]: FirstRunGui was created.
[Log 02:28:54.3757540]: Remote checking has been disabled for: TAC Fuel Balancer
[Log 02:28:54.3764620]: /mnt/ssd120/alex/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/TacFuelBalancer/TacFuelBalancer.version
	NAME: TAC Fuel Balancer
	URL: http://ksp.spacetux.net/avc/TacFuelBalancer
	DOWNLOAD: https://spacedock.info/mod/640/TacFuelBalancer
	GITHUB: NULL
	VERSION: 2.21.5.1
	KSP_VERSION: 1.8.1
	KSP_VERSION_MIN: 1.8
	KSP_VERSION_MAX: NULL
	CompatibleKspVersion: True
	CompatibleKspVersionMin: True
	CompatibleKspVersionMax: True
	CompatibleGitHubVersion: True

[Log 02:28:54.3787340]: FirstRunGui was destroyed.

Still not loaded.

**Comment by linuxgurugamer** [comment]
Thats from AVC.
First, delete all MiniAVC.dll files you can find, they are problematic.
Then, check to see if you have the dependencies installed.
If you still have a problem, please get me a log file
