### ISSUE TITLE
startup dependence FYI

### ISSUE THREAD

**Issue by histalonia** [linuxgurugamer/TacFuelBalancer#4]
It would be nice if ClickThroughBlocker and ToolbarControl are not installed, a reminder would be added at startup, as this is a fairly new dependency.  

With just TacFuelBalancer and MechJeb2 installed, KSP remains in the loading screen indefinately.  (it loads everything, but just never starts the game)
If module manager is added it will display an error about TacFuelBalancer not functioning with 1.8.1.

As the startup sequence is tricky I understand if this is not feasible as a code fix.  Perhaps a bold reminder on the download info screen.

**Comment by linuxgurugamer** [comment]
Not really doable.  However the game should not just hang.  Could you please get me a log file, sounds like there is a nullref at a critical point in the boot process
